i2c:
  sda: $sda
  scl: $scl
  scan: True

sensor:
  - platform: vl53l0x
    update_interval: 5s
    long_range: true
    accuracy_decimals: 2
    id: range_sensor
    internal: true

binary_sensor:
  - platform: template
    id: garage_door_range_sensor
    internal: true
    lambda: |-
      if (std::isnan(id(range_sensor).state) || id(range_sensor).state > $open_garage_door_distance_from_ceiling + $open_garage_door_distance_margin_of_error) {
        return false;
      } else if (id(range_sensor).state > $open_garage_door_distance_from_ceiling - $open_garage_door_distance_margin_of_error){
        return true;
      } else {
        return {};
      }
